### ISSUE TITLE
Unexpected Result

### ISSUE THREAD

**Issue by brycemorrow4564** [Bishalsarang/Recursion-Tree-Visualizer#10]
Hello! First of all I think this is a really interesting little tool. I'm thinking about launching a youtube channel where I cover solutions to common interview questions in depth and this could potentially be very useful. 

I've got the package installed and working correctly (ran it on fibonacci demo and got the expected result) but when I used it with one of my own functions I got something unexpected. 

I've included the code I was running and the output image. The code is for generating all permutations over an input array. The output graph is a series of disconnected components which doesn't make sense to me. 

![Screen Shot 2020-10-31 at 2 52 36 PM](https://user-images.githubusercontent.com/9085296/97787502-0f886a80-1b89-11eb-8c89-905c549da6d3.png)

![permutations](https://user-images.githubusercontent.com/9085296/97787523-2a5adf00-1b89-11eb-87f8-1be7a36565ff.png)

**Comment by Bishalsarang** [comment]
Sorry for the late reply. I have been busy lately.
I'll look into the issue and get back to you. 

In the meantime you can view the code from example section and see if that can be of any help.

**Comment by Bishalsarang** [comment]
The issue is when we mutate the function argument.
![perm](https://user-images.githubusercontent.com/11006583/98498815-f27e2680-226f-11eb-9cfe-ddb5cf1bb3a2.png)
I have removed the parameter res from the drawing for testing purposes. 

Is it the expected diagram? we can make the package work with the above case too.
If you verify then I can implement the feature within this week.
@brycemorrow4564
